version '3.5'

services
  etcd
    container_name milvus-etcd
    image quay.iocoreosetcdv3.5.5
    environment
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes
      - ${DOCKER_VOLUME_DIRECTORY-.}volumesetcdetcd
    command etcd -advertise-client-urls=http127.0.0.12379 -listen-client-urls http0.0.0.02379 --data-dir etcd

  minio
    container_name milvus-minio
    image miniominioRELEASE.2023-03-20T20-16-18Z
    environment
      MINIO_ACCESS_KEY minioadmin
      MINIO_SECRET_KEY minioadmin
    volumes
      - ${DOCKER_VOLUME_DIRECTORY-.}volumesminiominio_data
    command minio server minio_data
    healthcheck
      test [CMD, curl, -f, httplocalhost9000miniohealthlive]
      interval 30s
      timeout 20s
      retries 3

  standalone
    container_name milvus-standalone
    image milvusdbmilvusv2.2.11
    command [milvus, run, standalone]
    environment
      ETCD_ENDPOINTS etcd2379
      MINIO_ADDRESS minio9000
    volumes
      - ${DOCKER_VOLUME_DIRECTORY-.}volumesmilvusvarlibmilvus
    ports
      - 1953019530
      - 90919091
    depends_on
      - etcd
      - minio

  pdf_qa_app
    build .
    ports
      - 85018501
    environment
      - COHERE_API_KEY=${COHERE_API_KEY}
    volumes
      - .app
    depends_on
      - standalone

volumes
  etcd
  minio
  milvus